name-template: $NEXT_PATCH_VERSION.RELEASE
tag-template: $NEXT_PATCH_VERSION.RELEASE
template: |
    # What's Changed

    $CHANGES
categories:
  - title: 🚀 Features / Enhancements
    label: type/enhancement
  - title: 🐛 Bug Fixes
    label: type/bug
  - title: 📖 Documentation
    label: type/documentation
  - title: 🧹 Housekeeping
    label: type/chore
  - title: 📦 Dependency updates
    label: type/dependency-upgrade

