pr: none
trigger:
  batch: false
  branches:
    exclude: [ '*' ]
  tags:
    include: [ '*' ]

jobs:
- job: publish
  displayName: Publish
  pool:
    name: 'Hosted Ubuntu 1604'
  steps:
  - bash: ./gradlew --no-daemon -Pversion=$(git tag --points-at HEAD) publish
    env:
      ${{ if not(endsWith(variables['Build.SourceBranch'], '.RELEASE')) }}:
        GRADLE_PUBLISH_REPO_URL: https://repo.spring.io/libs-milestone-local/
        GRADLE_PUBLISH_MAVEN_USER: $(artifactory.username)
        GRADLE_PUBLISH_MAVEN_PASSWORD: $(artifactory.password)
      ${{ if endsWith(variables['Build.SourceBranch'], '.RELEASE') }}:
        GRADLE_PUBLISH_REPO_URL: https://api.bintray.com/maven/spring/jars/BlockHound/
        GRADLE_PUBLISH_MAVEN_USER: $(bintray.user)
        GRADLE_PUBLISH_MAVEN_PASSWORD: $(bintray.apiKey)
